/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 6
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_word = 1,
  anon_sym_POUND = 2,
  aux_sym_comment_token1 = 3,
  anon_sym_SEMI = 4,
  aux_sym__terminator_token1 = 5,
  sym_program = 6,
  sym__statements = 7,
  sym__statement = 8,
  sym_command = 9,
  sym_command_name = 10,
  sym_argument = 11,
  sym_comment = 12,
  sym__terminator = 13,
  aux_sym_program_repeat1 = 14,
  aux_sym__statements_repeat1 = 15,
  aux_sym_command_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_word] = "word",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SEMI] = ";",
  [aux_sym__terminator_token1] = "_terminator_token1",
  [sym_program] = "program",
  [sym__statements] = "_statements",
  [sym__statement] = "_statement",
  [sym_command] = "command",
  [sym_command_name] = "command_name",
  [sym_argument] = "argument",
  [sym_comment] = "comment",
  [sym__terminator] = "_terminator",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym__statements_repeat1] = "_statements_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_word] = sym_word,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym__terminator_token1] = aux_sym__terminator_token1,
  [sym_program] = sym_program,
  [sym__statements] = sym__statements,
  [sym__statement] = sym__statement,
  [sym_command] = sym_command,
  [sym_command_name] = sym_command_name,
  [sym_argument] = sym_argument,
  [sym_comment] = sym_comment,
  [sym__terminator] = sym__terminator,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym__statements_repeat1] = aux_sym__statements_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__terminator_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__statements] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_command_name] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__terminator] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statements_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == ';') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(2);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym_word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(2);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym__terminator_token1);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(1),
    [aux_sym__terminator_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(22),
    [sym__statements] = STATE(21),
    [sym__statement] = STATE(11),
    [sym_command] = STATE(16),
    [sym_command_name] = STATE(3),
    [sym_comment] = STATE(1),
    [sym__terminator] = STATE(10),
    [aux_sym_program_repeat1] = STATE(2),
    [aux_sym__statements_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_word] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(9),
    [aux_sym__terminator_token1] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__statements] = STATE(24),
    [sym__statement] = STATE(11),
    [sym_command] = STATE(16),
    [sym_command_name] = STATE(3),
    [sym_comment] = STATE(2),
    [sym__terminator] = STATE(10),
    [aux_sym_program_repeat1] = STATE(5),
    [aux_sym__statements_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_word] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(9),
    [aux_sym__terminator_token1] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      sym_word,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_command_repeat1,
    STATE(13), 1,
      sym_argument,
    ACTIONS(13), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [21] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      sym_word,
    STATE(4), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_command_repeat1,
    STATE(13), 1,
      sym_argument,
    ACTIONS(17), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [42] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(10), 1,
      sym__terminator,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      sym_word,
    ACTIONS(21), 2,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
    STATE(5), 2,
      sym_comment,
      aux_sym_program_repeat1,
  [61] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(26), 1,
      sym_word,
    STATE(13), 1,
      sym_argument,
    STATE(6), 2,
      sym_comment,
      aux_sym_command_repeat1,
    ACTIONS(24), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [80] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_word,
    STATE(3), 1,
      sym_command_name,
    STATE(7), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym__statements_repeat1,
    STATE(15), 1,
      sym__statement,
    STATE(16), 1,
      sym_command,
  [102] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(29), 1,
      sym_word,
    STATE(3), 1,
      sym_command_name,
    STATE(16), 1,
      sym_command,
    STATE(17), 1,
      sym__statement,
    STATE(8), 2,
      sym_comment,
      aux_sym__statements_repeat1,
  [122] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(9), 1,
      sym_comment,
    ACTIONS(32), 4,
      ts_builtin_sym_end,
      sym_word,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [135] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(10), 1,
      sym_comment,
    ACTIONS(34), 4,
      ts_builtin_sym_end,
      sym_word,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [148] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_comment,
    STATE(18), 1,
      sym__terminator,
    ACTIONS(9), 2,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [165] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(12), 1,
      sym_comment,
    ACTIONS(38), 4,
      ts_builtin_sym_end,
      sym_word,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [178] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(13), 1,
      sym_comment,
    ACTIONS(40), 4,
      ts_builtin_sym_end,
      sym_word,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [191] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(14), 1,
      sym_comment,
    ACTIONS(42), 4,
      ts_builtin_sym_end,
      sym_word,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [204] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      sym_comment,
    STATE(19), 1,
      sym__terminator,
    ACTIONS(9), 2,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [221] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(16), 1,
      sym_comment,
    ACTIONS(46), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [233] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(17), 1,
      sym_comment,
    STATE(23), 1,
      sym__terminator,
    ACTIONS(9), 2,
      anon_sym_SEMI,
      aux_sym__terminator_token1,
  [247] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      sym_word,
    STATE(18), 1,
      sym_comment,
  [260] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(48), 1,
      sym_word,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym_comment,
  [273] = 3,
    ACTIONS(52), 1,
      anon_sym_POUND,
    ACTIONS(54), 1,
      aux_sym_comment_token1,
    STATE(20), 1,
      sym_comment,
  [283] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(21), 1,
      sym_comment,
  [293] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      sym_comment,
  [303] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(48), 1,
      sym_word,
    STATE(23), 1,
      sym_comment,
  [313] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      sym_comment,
  [323] = 1,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 21,
  [SMALL_STATE(5)] = 42,
  [SMALL_STATE(6)] = 61,
  [SMALL_STATE(7)] = 80,
  [SMALL_STATE(8)] = 102,
  [SMALL_STATE(9)] = 122,
  [SMALL_STATE(10)] = 135,
  [SMALL_STATE(11)] = 148,
  [SMALL_STATE(12)] = 165,
  [SMALL_STATE(13)] = 178,
  [SMALL_STATE(14)] = 191,
  [SMALL_STATE(15)] = 204,
  [SMALL_STATE(16)] = 221,
  [SMALL_STATE(17)] = 233,
  [SMALL_STATE(18)] = 247,
  [SMALL_STATE(19)] = 260,
  [SMALL_STATE(20)] = 273,
  [SMALL_STATE(21)] = 283,
  [SMALL_STATE(22)] = 293,
  [SMALL_STATE(23)] = 303,
  [SMALL_STATE(24)] = 313,
  [SMALL_STATE(25)] = 323,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__terminator, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_name, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [56] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kakscript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "kakscript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
